### PR TITLE
Request for review of Tor implementation

### PR DESCRIPTION
**Pull request by azuk4r**

### CODE REVIEW

**Comment by azuk4r** [comment]
I'm telling you because you made a comment before stating an adjustment that I had made... maybe you were seeing a previous version

**Comment by azuk4r** [comment]
Oh I see! That is very good, I'm glad I helped you find that approach! Brilliant. Anything, write to me through X!

**Comment by azuk4r** [comment]
I just reviewed the README for your project and I agree that it is an elegant way to run it. I will also leave this polished version in the next few days, in case you want to recap!

**Comment by 0x-Apollyon** [comment]
No the stuff I was talking about is that your fork runs tor by itself on the users computer
I think that piece can cause issues and make it not work in certain environments
Thats why I have left the task of running and setting up tor for the user to do manually

**Comment by 0x-Apollyon** [comment]
I have added your project to the readme so if someone has to run tor without setting it up manually they can use your version

**Comment by azuk4r** [comment]
btw I updated my readme to make it clear that it is an early version of your project, I made it BIG so that it can be seen (with redirection to your project). Anything, I'm here, I'll resume projects in the next few days but I can always try to find some time! I will be watching your project, very interesting! Have a very good week

**Comment by azuk4r** [comment]
I dont understand what you mean with "your fork runs tor by itself on the users computer"

tor has not run by itself in my commit. 

are you sure you already check all? weird

**Comment by azuk4r** [comment]
Its okey but in tor_manager.py you can find:

def start_tor_service():
	global tor_executable

	if os.name == "nt":
		tor_executable = "C:\\Tor\\tor\\tor.exe"
	elif sys.platform == "darwin":
		tor_executable = "/opt/homebrew/bin/tor"
		if not os.path.exists(tor_executable):
			tor_executable = "/usr/local/bin/tor"
	else:
		tor_executable = "/usr/bin/tor"

	if not os.path.exists(tor_executable):
		print("[X] TOR EXECUTABLE NOT FOUND\n[?] MAKE SURE YOU HAVE TOR INSTALLED")
		sys.exit(1)

	if not is_tor_running():
		print("[!] TOR IS NOT RUNNING\n[X] PLEASE START THE TOR SERVICE AND TRY AGAIN")
		sys.exit(1)
	else:
		print("[*] TOR IS RUNNING"
		
		
**The paths declaration is for working with the stem module not running.**

**Pull request closed without merging**
