### PR TITLE
Added Tor support, Tor IP rotation and cookies/blockers warns

### PR DESCRIPTION
**Pull request by azuk4r**

### CODE REVIEW

**Comment by 0x-Apollyon** [comment]
The TOR manager seems to be coded to only work if

1) TOR is installed
2) Only on linux systems

Also the code try to launches TOR as sudo .

Make it so it checks wether TOR is running and doesnt actually run it. If it is running it goes ahead and if it isnt it prompts the user to run tor. Make this work on windows and macos too.

As for proxy rotation, the ways proxies are currently implemented already randomizes the proxy is better than rotation in my opinion.

**Comment by 0x-Apollyon** [comment]
Once you have done the requested changes, lmk

**Comment by azuk4r** [comment]
.

**Comment by azuk4r** [comment]
.

**Comment by 0x-Apollyon** [comment]
Nah nah no need to apologise mate
You can make rotation default of using tor and make the argument something like
```
--tor {number_here/disable}
```
where the number_here is the number of requests after which the tor ip is rotated and if it is sent as "disable" then the ip isnt rotated

**Comment by 0x-Apollyon** [comment]
so if it run it as this it doesnt rotate the tor connection
```
python LFIscanner.py -u https://example.com -p all_os.txt --tor disable
```

however if its this it rotates every 100 requests
```
python LFIscanner.py -u https://example.com -p all_os.txt --tor 100
```

**Comment by azuk4r** [comment]
.

**Comment by azuk4r** [comment]
.

**Comment by azuk4r** [comment]
.

**Comment by 0x-Apollyon** [comment]
> hey mate, question: for print detected LFI, do you need all 3 conditionals of root, bash and /bin at the same time?
> 
> if ‘root’ and ‘bash’ and r‘/bin’ in query.text and query.status_code // 100 == 2:
> 
> if that's the case, this might be more correct.
> 
> if all(keyword in query.text for keyword in [‘root’, ‘bash’, ‘/bin’]) and query.status_code // 100 == 2:
> 
> i'm asking because a target that was giving me results is now not giving me results, so i just want to confirm that the conditions to activate it are correct or if we have some kind of conflict. it's really been a couple of days since it stopped giving me positive results and i'm testing targets with known vuln, so it seems strange to me that nothing is being printed.
> 
> please, when you can confirm if my suspicions are incorrect or if there was some kind of error in this verification.
> 
> I made a correction to work the load splitting correctly in case of odd threads, it is possible that there are other parts of the code that also need this adjustment: process to test with -t 16 instead of 15, to confirm if this is the error.
> 
> I'll keep testing and will post if successful.
> 
> PS: today I start with the tuning for other OS, first I need to finish with my paranoid test routine.

Yo thanks a lot for reporting this
This seems to be a bug from the orignal tool YA-LFI is based on
Will fix it in the next commit
Also I told you that YA-LFI shouldnt try to run tor itself, it should only check if tor is running and if it isnt it should tell the user to run tor

**Comment by azuk4r** [comment]
.

**Comment by 0x-Apollyon** [comment]
Yo I thought a better way to do tor by just treat it as a proxy and not running it
I have mentioned your fork of YA-LFI in the readme so people can check it out aswell
Thanks a lot for the suggestions and being a tester
Closing this pr for now, lmk if you add new features or any more ideas

**Pull request closed without merging**
